name = "meeting-summarizer"
main = "functions/summarize.js"
compatibility_date = "2024-03-25"

[vars]
GROQ_API_KEY = "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"

[env.production]
route = "meeting-summarizer.nileshdotin.workers.dev/*"